// Logos: a picture laid flat over the frame.
//
// A logo is not a card. Cards are generated by the component and live in 3D;
// a logo sits on the glass in front of everything, in the same coordinate
// space as a text layer — a percentage of the frame, so it lands in the same
// place at every export size.

import type { LogoLayer, MotionDoc } from '../../../../shared/motion/types'
import { Section, SliderRow } from './controls'
import type { Keyer } from '../../lib/motion/keying'

export function LogoSection({
  doc, onChange, keyer
}: {
  doc: MotionDoc
  onChange: (patch: Partial<MotionDoc>) => void
  keyer?: Keyer
}): React.JSX.Element {
  const logos = doc.visual.logos
  const setLogos = (next: LogoLayer[]): void => onChange({ visual: { ...doc.visual, logos: next } })
  const usable = doc.visual.images

  return (
    <Section
      title="Logo"
      defaultOpen={false}
      right={
        <button
          type="button"
          disabled={usable.length === 0}
          onClick={() => {
            const first = usable[0]
            if (!first) return
            setLogos([
              ...logos,
              { id: `logo-${Date.now()}`, imageId: first.id, size: 18, opacity: 100, x: 50, y: 88 }
            ])
          }}
          className="rounded-sm px-1.5 py-0.5 text-[10.5px] text-text-muted hover:bg-raised hover:text-text-primary disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/60"
        >
          Add
        </button>
      }
    >
      {usable.length === 0 ? (
        <p className="text-[11px] text-text-muted">
          Add a picture first.
        </p>
      ) : null}
      {logos.map((layer, i) => {
        const setLayer = (patch: Partial<LogoLayer>): void =>
          setLogos(logos.map((l, j) => (j === i ? { ...l, ...patch } : l)))
        return (
          <div key={layer.id} className="flex flex-col gap-2 rounded-md bg-sunken p-2">
            <div className="flex items-center gap-1">
              <select
                value={layer.imageId}
                onChange={(e) => setLayer({ imageId: e.target.value })}
                aria-label={`Picture for logo ${i + 1}`}
                className="min-w-0 flex-1 rounded-sm bg-bg px-1.5 py-1 text-[11.5px] text-text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/60"
              >
                {usable.map((img) => (
                  <option key={img.id} value={img.id}>{img.name}</option>
                ))}
              </select>
              <button
                type="button"
                onClick={() => setLogos(logos.filter((_, j) => j !== i))}
                aria-label={`Remove logo ${i + 1}`}
                className="rounded-sm px-1.5 py-1 text-[10.5px] text-text-muted hover:text-error focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/60"
              >
                ×
              </button>
            </div>
            <SliderRow label="Size" value={layer.size} min={1} max={100} step={0.5} onChange={(v) => setLayer({ size: v })} keyframe={keyer?.(`logo:${layer.id}:size`, layer.size)} />
            <SliderRow label="Across" value={layer.x} min={0} max={100} step={0.5} onChange={(v) => setLayer({ x: v })} keyframe={keyer?.(`logo:${layer.id}:x`, layer.x)} />
            <SliderRow label="Down" value={layer.y} min={0} max={100} step={0.5} onChange={(v) => setLayer({ y: v })} keyframe={keyer?.(`logo:${layer.id}:y`, layer.y)} />
            <SliderRow label="Opacity" value={layer.opacity} min={0} max={100} step={1} onChange={(v) => setLayer({ opacity: v })} keyframe={keyer?.(`logo:${layer.id}:opacity`, layer.opacity)} />
          </div>
        )
      })}
    </Section>
  )
}
